# Generated by Django 4.2.5 on 2023-10-12 05:29

import busapp1.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "departure_time",
                    models.DateTimeField(default=busapp1.models.default_departure_time),
                ),
                ("total_seats", models.IntegerField()),
                ("available_seats", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="BusRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Some Default Name", max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "address",
                    models.CharField(default="Some Default Value", max_length=200),
                ),
                ("message", models.TextField(default="Some Default Message")),
            ],
        ),
        migrations.CreateModel(
            name="BusSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_time", models.TimeField()),
                (
                    "arrival_time",
                    models.TimeField(default=busapp1.models.get_current_time),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="busapp1.busroute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_tickets", models.IntegerField()),
                ("booking_time", models.DateTimeField()),
                ("name", models.CharField(default="Unknown", max_length=255)),
                ("address", models.TextField(default="Unknown")),
                ("phone", models.CharField(default="Unknown", max_length=15)),
                ("age", models.IntegerField(default=0)),
                ("seat_number", models.IntegerField(null=True)),
                (
                    "ticket_number",
                    models.CharField(default="Unknown", max_length=10, unique=True),
                ),
                (
                    "ticket_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="busapp1.bus"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
