# Generated by Django 4.2.5 on 2023-10-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("busapp1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="seat_number",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
