# Generated by Django 4.2.5 on 2023-10-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("busapp1", "0002_alter_booking_seat_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="seat_number",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="ticket_price",
        ),
        migrations.AddField(
            model_name="bus",
            name="seat_number",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="ticket_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
