# Generated by Django 4.2.5 on 2023-10-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("busapp1", "0003_remove_booking_seat_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
