# Generated by Django 4.2.5 on 2023-10-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("busapp1", "0004_booking_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="seat_number",
        ),
        migrations.AddField(
            model_name="booking",
            name="seat_number",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
