# Generated by Django 4.2.5 on 2023-10-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("busapp1", "0005_remove_bus_seat_number_booking_seat_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="address",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="booking",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="booking",
            name="phone",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="booking",
            name="ticket_number",
            field=models.CharField(default="", max_length=10, unique=True),
        ),
    ]
