# Generated by Django 4.2.5 on 2023-10-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("busapp1", "0006_alter_booking_address_alter_booking_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="num_tickets",
            field=models.IntegerField(default=1),
        ),
    ]
